zmmailbox -z -m raioxhsga@cruzeiro.rs.gov.br -t 0 postRestURL "//?fmt=tgz&resolve=skip" /tmp/raioxhsga@cruzeiro.rs.gov.br-Trash.tgz
zmmailbox -z -m medicoshsga@cruzeiro.rs.gov.br -t 0 postRestURL "//?fmt=tgz&resolve=skip" /tmp/medicoshsga@cruzeiro.rs.gov.br-Trash.tgz
zmmailbox -z -m enfermagemhsga@cruzeiro.rs.gov.br -t 0 postRestURL "//?fmt=tgz&resolve=skip" /tmp/enfermagemhsga@cruzeiro.rs.gov.br-Trash.tgz
zmmailbox -z -m agendamentox@cruzeiro.rs.gov.br -t 0 postRestURL "//?fmt=tgz&resolve=skip" /tmp/agendamentox@cruzeiro.rs.gov.br-Trash.tgz
zmmailbox -z -m atendimento@cruzeiro.rs.gov.br -t 0 postRestURL "//?fmt=tgz&resolve=skip" /tmp/atendimento@cruzeiro.rs.gov.br-Trash.tgz
zmmailbox -z -m saude2@cruzeiro.rs.gov.br -t 0 postRestURL "//?fmt=tgz&resolve=skip" /tmp/saude2@cruzeiro.rs.gov.br-Trash.tgz
zmmailbox -z -m planejamento@cruzeiro.rs.gov.br -t 0 postRestURL "//?fmt=tgz&resolve=skip" /tmp/planejamento@cruzeiro.rs.gov.br-Trash.tgz
zmmailbox -z -m enfermagemx@cruzeiro.rs.gov.br -t 0 postRestURL "//?fmt=tgz&resolve=skip" /tmp/enfermagemx@cruzeiro.rs.gov.br-Trash.tgz
zmmailbox -z -m farmacias@cruzeiro.rs.gov.br -t 0 postRestURL "//?fmt=tgz&resolve=skip" /tmp/farmacias@cruzeiro.rs.gov.br-Trash.tgz
zmmailbox -z -m licita2@cruzeiro.rs.gov.br -t 0 postRestURL "//?fmt=tgz&resolve=skip" /tmp/licita2@cruzeiro.rs.gov.br-Trash.tgz
zmmailbox -z -m sec.saude@cruzeiro.rs.gov.br -t 0 postRestURL "//?fmt=tgz&resolve=skip" /tmp/sec.saude@cruzeiro.rs.gov.br-Trash.tgz
zmmailbox -z -m compras@cruzeiro.rs.gov.br -t 0 postRestURL "//?fmt=tgz&resolve=skip" /tmp/compras@cruzeiro.rs.gov.br-Trash.tgz
zmmailbox -z -m compras2@cruzeiro.rs.gov.br -t 0 postRestURL "//?fmt=tgz&resolve=skip" /tmp/compras2@cruzeiro.rs.gov.br-Trash.tgz
zmmailbox -z -m sistemasaude@cruzeiro.rs.gov.br -t 0 postRestURL "//?fmt=tgz&resolve=skip" /tmp/sistemasaude@cruzeiro.rs.gov.br-Trash.tgz
zmmailbox -z -m tributos@cruzeiro.rs.gov.br -t 0 postRestURL "//?fmt=tgz&resolve=skip" /tmp/tributos@cruzeiro.rs.gov.br-Trash.tgz
zmmailbox -z -m tributos3@cruzeiro.rs.gov.br -t 0 postRestURL "//?fmt=tgz&resolve=skip" /tmp/tributos3@cruzeiro.rs.gov.br-Trash.tgz
zmmailbox -z -m agricultura2x@cruzeiro.rs.gov.br -t 0 postRestURL "//?fmt=tgz&resolve=skip" /tmp/agricultura2x@cruzeiro.rs.gov.br-Trash.tgz
zmmailbox -z -m meioambiente3@cruzeiro.rs.gov.br -t 0 postRestURL "//?fmt=tgz&resolve=skip" /tmp/meioambiente3@cruzeiro.rs.gov.br-Trash.tgz
zmmailbox -z -m empenho@cruzeiro.rs.gov.br -t 0 postRestURL "//?fmt=tgz&resolve=skip" /tmp/empenho@cruzeiro.rs.gov.br-Trash.tgz
zmmailbox -z -m tesouraria@cruzeiro.rs.gov.br -t 0 postRestURL "//?fmt=tgz&resolve=skip" /tmp/tesouraria@cruzeiro.rs.gov.br-Trash.tgz
zmmailbox -z -m icms@cruzeiro.rs.gov.br -t 0 postRestURL "//?fmt=tgz&resolve=skip" /tmp/icms@cruzeiro.rs.gov.br-Trash.tgz
zmmailbox -z -m educa@cruzeiro.rs.gov.br -t 0 postRestURL "//?fmt=tgz&resolve=skip" /tmp/educa@cruzeiro.rs.gov.br-Trash.tgz
zmmailbox -z -m procuradoria@cruzeiro.rs.gov.br -t 0 postRestURL "//?fmt=tgz&resolve=skip" /tmp/procuradoria@cruzeiro.rs.gov.br-Trash.tgz
zmmailbox -z -m contabilidade@cruzeiro.rs.gov.br -t 0 postRestURL "//?fmt=tgz&resolve=skip" /tmp/contabilidade@cruzeiro.rs.gov.br-Trash.tgz
zmmailbox -z -m agricultura@cruzeiro.rs.gov.br -t 0 postRestURL "//?fmt=tgz&resolve=skip" /tmp/agricultura@cruzeiro.rs.gov.br-Trash.tgz
zmmailbox -z -m esf1@cruzeiro.rs.gov.br -t 0 postRestURL "//?fmt=tgz&resolve=skip" /tmp/esf1@cruzeiro.rs.gov.br-Trash.tgz
zmmailbox -z -m esf2@cruzeiro.rs.gov.br -t 0 postRestURL "//?fmt=tgz&resolve=skip" /tmp/esf2@cruzeiro.rs.gov.br-Trash.tgz
zmmailbox -z -m fiscal2@cruzeiro.rs.gov.br -t 0 postRestURL "//?fmt=tgz&resolve=skip" /tmp/fiscal2@cruzeiro.rs.gov.br-Trash.tgz
zmmailbox -z -m nutricao@cruzeiro.rs.gov.br -t 0 postRestURL "//?fmt=tgz&resolve=skip" /tmp/nutricao@cruzeiro.rs.gov.br-Trash.tgz
zmmailbox -z -m licita@cruzeiro.rs.gov.br -t 0 postRestURL "//?fmt=tgz&resolve=skip" /tmp/licita@cruzeiro.rs.gov.br-Trash.tgz
zmmailbox -z -m licitahsga@cruzeiro.rs.gov.br -t 0 postRestURL "//?fmt=tgz&resolve=skip" /tmp/licitahsga@cruzeiro.rs.gov.br-Trash.tgz
zmmailbox -z -m cultura@cruzeiro.rs.gov.br -t 0 postRestURL "//?fmt=tgz&resolve=skip" /tmp/cultura@cruzeiro.rs.gov.br-Trash.tgz
zmmailbox -z -m turismo@cruzeiro.rs.gov.br -t 0 postRestURL "//?fmt=tgz&resolve=skip" /tmp/turismo@cruzeiro.rs.gov.br-Trash.tgz
zmmailbox -z -m expocruzeiro@cruzeiro.rs.gov.br -t 0 postRestURL "//?fmt=tgz&resolve=skip" /tmp/expocruzeiro@cruzeiro.rs.gov.br-Trash.tgz
zmmailbox -z -m pessoalx@cruzeiro.rs.gov.br -t 0 postRestURL "//?fmt=tgz&resolve=skip" /tmp/pessoalx@cruzeiro.rs.gov.br-Trash.tgz
zmmailbox -z -m procuradoriaadjunta@cruzeiro.rs.gov.br -t 0 postRestURL "//?fmt=tgz&resolve=skip" /tmp/procuradoriaadjunta@cruzeiro.rs.gov.br-Trash.tgz
zmmailbox -z -m esporte@cruzeiro.rs.gov.br -t 0 postRestURL "//?fmt=tgz&resolve=skip" /tmp/esporte@cruzeiro.rs.gov.br-Trash.tgz
zmmailbox -z -m procuradoriageral@cruzeiro.rs.gov.br -t 0 postRestURL "//?fmt=tgz&resolve=skip" /tmp/procuradoriageral@cruzeiro.rs.gov.br-Trash.tgz
zmmailbox -z -m saudemental@cruzeiro.rs.gov.br -t 0 postRestURL "//?fmt=tgz&resolve=skip" /tmp/saudemental@cruzeiro.rs.gov.br-Trash.tgz
zmmailbox -z -m assessoriajuridica@cruzeiro.rs.gov.br -t 0 postRestURL "//?fmt=tgz&resolve=skip" /tmp/assessoriajuridica@cruzeiro.rs.gov.br-Trash.tgz
zmmailbox -z -m assistencia@cruzeiro.rs.gov.br -t 0 postRestURL "//?fmt=tgz&resolve=skip" /tmp/assistencia@cruzeiro.rs.gov.br-Trash.tgz
zmmailbox -z -m cras@cruzeiro.rs.gov.br -t 0 postRestURL "//?fmt=tgz&resolve=skip" /tmp/cras@cruzeiro.rs.gov.br-Trash.tgz
zmmailbox -z -m cpd@cruzeiro.rs.gov.br -t 0 postRestURL "//?fmt=tgz&resolve=skip" /tmp/cpd@cruzeiro.rs.gov.br-Trash.tgz
zmmailbox -z -m gabinete@cruzeiro.rs.gov.br -t 0 postRestURL "//?fmt=tgz&resolve=skip" /tmp/gabinete@cruzeiro.rs.gov.br-Trash.tgz
zmmailbox -z -m assessorprocuradoria@cruzeiro.rs.gov.br -t 0 postRestURL "//?fmt=tgz&resolve=skip" /tmp/assessorprocuradoria@cruzeiro.rs.gov.br-Trash.tgz
zmmailbox -z -m meioambiente@cruzeiro.rs.gov.br -t 0 postRestURL "//?fmt=tgz&resolve=skip" /tmp/meioambiente@cruzeiro.rs.gov.br-Trash.tgz
zmmailbox -z -m exames@cruzeiro.rs.gov.br -t 0 postRestURL "//?fmt=tgz&resolve=skip" /tmp/exames@cruzeiro.rs.gov.br-Trash.tgz
zmmailbox -z -m ivz2@cruzeiro.rs.gov.br -t 0 postRestURL "//?fmt=tgz&resolve=skip" /tmp/ivz2@cruzeiro.rs.gov.br-Trash.tgz
zmmailbox -z -m postoivz@cruzeiro.rs.gov.br -t 0 postRestURL "//?fmt=tgz&resolve=skip" /tmp/postoivz@cruzeiro.rs.gov.br-Trash.tgz
zmmailbox -z -m transito@cruzeiro.rs.gov.br -t 0 postRestURL "//?fmt=tgz&resolve=skip" /tmp/transito@cruzeiro.rs.gov.br-Trash.tgz
zmmailbox -z -m faturamento2hsga@cruzeiro.rs.gov.br -t 0 postRestURL "//?fmt=tgz&resolve=skip" /tmp/faturamento2hsga@cruzeiro.rs.gov.br-Trash.tgz
zmmailbox -z -m farmaciahsga@cruzeiro.rs.gov.br -t 0 postRestURL "//?fmt=tgz&resolve=skip" /tmp/farmaciahsga@cruzeiro.rs.gov.br-Trash.tgz
zmmailbox -z -m comprashsga@cruzeiro.rs.gov.br -t 0 postRestURL "//?fmt=tgz&resolve=skip" /tmp/comprashsga@cruzeiro.rs.gov.br-Trash.tgz
zmmailbox -z -m faturamentohsga@cruzeiro.rs.gov.br -t 0 postRestURL "//?fmt=tgz&resolve=skip" /tmp/faturamentohsga@cruzeiro.rs.gov.br-Trash.tgz
zmmailbox -z -m engenharia@cruzeiro.rs.gov.br -t 0 postRestURL "//?fmt=tgz&resolve=skip" /tmp/engenharia@cruzeiro.rs.gov.br-Trash.tgz
zmmailbox -z -m arquitetura@cruzeiro.rs.gov.br -t 0 postRestURL "//?fmt=tgz&resolve=skip" /tmp/arquitetura@cruzeiro.rs.gov.br-Trash.tgz
zmmailbox -z -m arquitetura2@cruzeiro.rs.gov.br -t 0 postRestURL "//?fmt=tgz&resolve=skip" /tmp/arquitetura2@cruzeiro.rs.gov.br-Trash.tgz
zmmailbox -z -m conselhotutelar@cruzeiro.rs.gov.br -t 0 postRestURL "//?fmt=tgz&resolve=skip" /tmp/conselhotutelar@cruzeiro.rs.gov.br-Trash.tgz
zmmailbox -z -m servicos@cruzeiro.rs.gov.br -t 0 postRestURL "//?fmt=tgz&resolve=skip" /tmp/servicos@cruzeiro.rs.gov.br-Trash.tgz
zmmailbox -z -m aviso@cruzeiro.rs.gov.br -t 0 postRestURL "//?fmt=tgz&resolve=skip" /tmp/aviso@cruzeiro.rs.gov.br-Trash.tgz
zmmailbox -z -m emefpassodeestrela@cruzeiro.rs.gov.br -t 0 postRestURL "//?fmt=tgz&resolve=skip" /tmp/emefpassodeestrela@cruzeiro.rs.gov.br-Trash.tgz
zmmailbox -z -m emefsaofelipe@cruzeiro.rs.gov.br -t 0 postRestURL "//?fmt=tgz&resolve=skip" /tmp/emefsaofelipe@cruzeiro.rs.gov.br-Trash.tgz
zmmailbox -z -m emeidoceinfancia@cruzeiro.rs.gov.br -t 0 postRestURL "//?fmt=tgz&resolve=skip" /tmp/emeidoceinfancia@cruzeiro.rs.gov.br-Trash.tgz
zmmailbox -z -m emeinovoscaminhos@cruzeiro.rs.gov.br -t 0 postRestURL "//?fmt=tgz&resolve=skip" /tmp/emeinovoscaminhos@cruzeiro.rs.gov.br-Trash.tgz
zmmailbox -z -m emeitrenzinhoalegre@cruzeiro.rs.gov.br -t 0 postRestURL "//?fmt=tgz&resolve=skip" /tmp/emeitrenzinhoalegre@cruzeiro.rs.gov.br-Trash.tgz
zmmailbox -z -m emeivilazwirtes@cruzeiro.rs.gov.br -t 0 postRestURL "//?fmt=tgz&resolve=skip" /tmp/emeivilazwirtes@cruzeiro.rs.gov.br-Trash.tgz
zmmailbox -z -m emeijacobsehn@cruzeiro.rs.gov.br -t 0 postRestURL "//?fmt=tgz&resolve=skip" /tmp/emeijacobsehn@cruzeiro.rs.gov.br-Trash.tgz
zmmailbox -z -m admhsga@cruzeiro.rs.gov.br -t 0 postRestURL "//?fmt=tgz&resolve=skip" /tmp/admhsga@cruzeiro.rs.gov.br-Trash.tgz
zmmailbox -z -m emef25dejulho@cruzeiro.rs.gov.br -t 0 postRestURL "//?fmt=tgz&resolve=skip" /tmp/emef25dejulho@cruzeiro.rs.gov.br-Trash.tgz
zmmailbox -z -m emefadelino@cruzeiro.rs.gov.br -t 0 postRestURL "//?fmt=tgz&resolve=skip" /tmp/emefadelino@cruzeiro.rs.gov.br-Trash.tgz
zmmailbox -z -m emefciceri@cruzeiro.rs.gov.br -t 0 postRestURL "//?fmt=tgz&resolve=skip" /tmp/emefciceri@cruzeiro.rs.gov.br-Trash.tgz
zmmailbox -z -m emefjacobsehn@cruzeiro.rs.gov.br -t 0 postRestURL "//?fmt=tgz&resolve=skip" /tmp/emefjacobsehn@cruzeiro.rs.gov.br-Trash.tgz
zmmailbox -z -m vigilanciasanitaria@cruzeiro.rs.gov.br -t 0 postRestURL "//?fmt=tgz&resolve=skip" /tmp/vigilanciasanitaria@cruzeiro.rs.gov.br-Trash.tgz
zmmailbox -z -m agendamento.passo@cruzeiro.rs.gov.br -t 0 postRestURL "//?fmt=tgz&resolve=skip" /tmp/agendamento.passo@cruzeiro.rs.gov.br-Trash.tgz
zmmailbox -z -m notafiscaleletronica@cruzeiro.rs.gov.br -t 0 postRestURL "//?fmt=tgz&resolve=skip" /tmp/notafiscaleletronica@cruzeiro.rs.gov.br-Trash.tgz
zmmailbox -z -m vigilanciaambiental@cruzeiro.rs.gov.br -t 0 postRestURL "//?fmt=tgz&resolve=skip" /tmp/vigilanciaambiental@cruzeiro.rs.gov.br-Trash.tgz
zmmailbox -z -m controleinterno@cruzeiro.rs.gov.br -t 0 postRestURL "//?fmt=tgz&resolve=skip" /tmp/controleinterno@cruzeiro.rs.gov.br-Trash.tgz
zmmailbox -z -m covid.passo@cruzeiro.rs.gov.br -t 0 postRestURL "//?fmt=tgz&resolve=skip" /tmp/covid.passo@cruzeiro.rs.gov.br-Trash.tgz
zmmailbox -z -m cras2@cruzeiro.rs.gov.br -t 0 postRestURL "//?fmt=tgz&resolve=skip" /tmp/cras2@cruzeiro.rs.gov.br-Trash.tgz
zmmailbox -z -m resultadoexameshsga@cruzeiro.rs.gov.br -t 0 postRestURL "//?fmt=tgz&resolve=skip" /tmp/resultadoexameshsga@cruzeiro.rs.gov.br-Trash.tgz
zmmailbox -z -m internet@cruzeiro.rs.gov.br -t 0 postRestURL "//?fmt=tgz&resolve=skip" /tmp/internet@cruzeiro.rs.gov.br-Trash.tgz
zmmailbox -z -m transporte@cruzeiro.rs.gov.br -t 0 postRestURL "//?fmt=tgz&resolve=skip" /tmp/transporte@cruzeiro.rs.gov.br-Trash.tgz
zmmailbox -z -m parque@cruzeiro.rs.gov.br -t 0 postRestURL "//?fmt=tgz&resolve=skip" /tmp/parque@cruzeiro.rs.gov.br-Trash.tgz
zmmailbox -z -m engenharial@cruzeiro.rs.gov.br -t 0 postRestURL "//?fmt=tgz&resolve=skip" /tmp/engenharial@cruzeiro.rs.gov.br-Trash.tgz
zmmailbox -z -m emergenciahsga@cruzeiro.rs.gov.br -t 0 postRestURL "//?fmt=tgz&resolve=skip" /tmp/emergenciahsga@cruzeiro.rs.gov.br-Trash.tgz
zmmailbox -z -m coordenacaosecsaude@cruzeiro.rs.gov.br -t 0 postRestURL "//?fmt=tgz&resolve=skip" /tmp/coordenacaosecsaude@cruzeiro.rs.gov.br-Trash.tgz
zmmailbox -z -m fiscal@cruzeiro.rs.gov.br -t 0 postRestURL "//?fmt=tgz&resolve=skip" /tmp/fiscal@cruzeiro.rs.gov.br-Trash.tgz
zmmailbox -z -m eliana@cruzeiro.rs.gov.br -t 0 postRestURL "//?fmt=tgz&resolve=skip" /tmp/eliana@cruzeiro.rs.gov.br-Trash.tgz
zmmailbox -z -m silvana@cruzeiro.rs.gov.br -t 0 postRestURL "//?fmt=tgz&resolve=skip" /tmp/silvana@cruzeiro.rs.gov.br-Trash.tgz
zmmailbox -z -m fabiane@cruzeiro.rs.gov.br -t 0 postRestURL "//?fmt=tgz&resolve=skip" /tmp/fabiane@cruzeiro.rs.gov.br-Trash.tgz
zmmailbox -z -m dalva@cruzeiro.rs.gov.br -t 0 postRestURL "//?fmt=tgz&resolve=skip" /tmp/dalva@cruzeiro.rs.gov.br-Trash.tgz
zmmailbox -z -m zeli@cruzeiro.rs.gov.br -t 0 postRestURL "//?fmt=tgz&resolve=skip" /tmp/zeli@cruzeiro.rs.gov.br-Trash.tgz
zmmailbox -z -m grasiela@cruzeiro.rs.gov.br -t 0 postRestURL "//?fmt=tgz&resolve=skip" /tmp/grasiela@cruzeiro.rs.gov.br-Trash.tgz
zmmailbox -z -m mirtes@cruzeiro.rs.gov.br -t 0 postRestURL "//?fmt=tgz&resolve=skip" /tmp/mirtes@cruzeiro.rs.gov.br-Trash.tgz
zmmailbox -z -m fernanda@cruzeiro.rs.gov.br -t 0 postRestURL "//?fmt=tgz&resolve=skip" /tmp/fernanda@cruzeiro.rs.gov.br-Trash.tgz
zmmailbox -z -m jaqueline@cruzeiro.rs.gov.br -t 0 postRestURL "//?fmt=tgz&resolve=skip" /tmp/jaqueline@cruzeiro.rs.gov.br-Trash.tgz
zmmailbox -z -m haide@cruzeiro.rs.gov.br -t 0 postRestURL "//?fmt=tgz&resolve=skip" /tmp/haide@cruzeiro.rs.gov.br-Trash.tgz
zmmailbox -z -m elis@cruzeiro.rs.gov.br -t 0 postRestURL "//?fmt=tgz&resolve=skip" /tmp/elis@cruzeiro.rs.gov.br-Trash.tgz
zmmailbox -z -m juliana@cruzeiro.rs.gov.br -t 0 postRestURL "//?fmt=tgz&resolve=skip" /tmp/juliana@cruzeiro.rs.gov.br-Trash.tgz
zmmailbox -z -m beatriz@cruzeiro.rs.gov.br -t 0 postRestURL "//?fmt=tgz&resolve=skip" /tmp/beatriz@cruzeiro.rs.gov.br-Trash.tgz
zmmailbox -z -m noemia@cruzeiro.rs.gov.br -t 0 postRestURL "//?fmt=tgz&resolve=skip" /tmp/noemia@cruzeiro.rs.gov.br-Trash.tgz
zmmailbox -z -m marli@cruzeiro.rs.gov.br -t 0 postRestURL "//?fmt=tgz&resolve=skip" /tmp/marli@cruzeiro.rs.gov.br-Trash.tgz
zmmailbox -z -m meioambiente2@cruzeiro.rs.gov.br -t 0 postRestURL "//?fmt=tgz&resolve=skip" /tmp/meioambiente2@cruzeiro.rs.gov.br-Trash.tgz
zmmailbox -z -m assistenciasocialsaude@cruzeiro.rs.gov.br -t 0 postRestURL "//?fmt=tgz&resolve=skip" /tmp/assistenciasocialsaude@cruzeiro.rs.gov.br-Trash.tgz
zmmailbox -z -m vigilanciaepidemiologica@cruzeiro.rs.gov.br -t 0 postRestURL "//?fmt=tgz&resolve=skip" /tmp/vigilanciaepidemiologica@cruzeiro.rs.gov.br-Trash.tgz
zmmailbox -z -m denunciascovid19@cruzeiro.rs.gov.br -t 0 postRestURL "//?fmt=tgz&resolve=skip" /tmp/denunciascovid19@cruzeiro.rs.gov.br-Trash.tgz
zmmailbox -z -m engenharia2@cruzeiro.rs.gov.br -t 0 postRestURL "//?fmt=tgz&resolve=skip" /tmp/engenharia2@cruzeiro.rs.gov.br-Trash.tgz
zmmailbox -z -m juntamilitar@cruzeiro.rs.gov.br -t 0 postRestURL "//?fmt=tgz&resolve=skip" /tmp/juntamilitar@cruzeiro.rs.gov.br-Trash.tgz
zmmailbox -z -m ti@cruzeiro.rs.gov.br -t 0 postRestURL "//?fmt=tgz&resolve=skip" /tmp/ti@cruzeiro.rs.gov.br-Trash.tgz
zmmailbox -z -m cmas@cruzeiro.rs.gov.br -t 0 postRestURL "//?fmt=tgz&resolve=skip" /tmp/cmas@cruzeiro.rs.gov.br-Trash.tgz
zmmailbox -z -m spfbl@cruzeiro.rs.gov.br -t 0 postRestURL "//?fmt=tgz&resolve=skip" /tmp/spfbl@cruzeiro.rs.gov.br-Trash.tgz
zmmailbox -z -m habitacao@cruzeiro.rs.gov.br -t 0 postRestURL "//?fmt=tgz&resolve=skip" /tmp/habitacao@cruzeiro.rs.gov.br-Trash.tgz
zmmailbox -z -m cartaosus@cruzeiro.rs.gov.br -t 0 postRestURL "//?fmt=tgz&resolve=skip" /tmp/cartaosus@cruzeiro.rs.gov.br-Trash.tgz
zmmailbox -z -m mariela@cruzeiro.rs.gov.br -t 0 postRestURL "//?fmt=tgz&resolve=skip" /tmp/mariela@cruzeiro.rs.gov.br-Trash.tgz
zmmailbox -z -m nilvarbc@cruzeiro.rs.gov.br -t 0 postRestURL "//?fmt=tgz&resolve=skip" /tmp/nilvarbc@cruzeiro.rs.gov.br-Trash.tgz
zmmailbox -z -m farmacia@cruzeiro.rs.gov.br -t 0 postRestURL "//?fmt=tgz&resolve=skip" /tmp/farmacia@cruzeiro.rs.gov.br-Trash.tgz
zmmailbox -z -m pregao@cruzeiro.rs.gov.br -t 0 postRestURL "//?fmt=tgz&resolve=skip" /tmp/pregao@cruzeiro.rs.gov.br-Trash.tgz
zmmailbox -z -m transportesaude@cruzeiro.rs.gov.br -t 0 postRestURL "//?fmt=tgz&resolve=skip" /tmp/transportesaude@cruzeiro.rs.gov.br-Trash.tgz
zmmailbox -z -m estagiariajuridico@cruzeiro.rs.gov.br -t 0 postRestURL "//?fmt=tgz&resolve=skip" /tmp/estagiariajuridico@cruzeiro.rs.gov.br-Trash.tgz
zmmailbox -z -m raioxhsga@cruzeiro.rs.gov.br -t 0 postRestURL "//?fmt=tgz&resolve=skip" /tmp/raioxhsga@cruzeiro.rs.gov.br-Junk.tgz
zmmailbox -z -m medicoshsga@cruzeiro.rs.gov.br -t 0 postRestURL "//?fmt=tgz&resolve=skip" /tmp/medicoshsga@cruzeiro.rs.gov.br-Junk.tgz
zmmailbox -z -m enfermagemhsga@cruzeiro.rs.gov.br -t 0 postRestURL "//?fmt=tgz&resolve=skip" /tmp/enfermagemhsga@cruzeiro.rs.gov.br-Junk.tgz
zmmailbox -z -m agendamentox@cruzeiro.rs.gov.br -t 0 postRestURL "//?fmt=tgz&resolve=skip" /tmp/agendamentox@cruzeiro.rs.gov.br-Junk.tgz
zmmailbox -z -m atendimento@cruzeiro.rs.gov.br -t 0 postRestURL "//?fmt=tgz&resolve=skip" /tmp/atendimento@cruzeiro.rs.gov.br-Junk.tgz
zmmailbox -z -m saude2@cruzeiro.rs.gov.br -t 0 postRestURL "//?fmt=tgz&resolve=skip" /tmp/saude2@cruzeiro.rs.gov.br-Junk.tgz
zmmailbox -z -m planejamento@cruzeiro.rs.gov.br -t 0 postRestURL "//?fmt=tgz&resolve=skip" /tmp/planejamento@cruzeiro.rs.gov.br-Junk.tgz
zmmailbox -z -m enfermagemx@cruzeiro.rs.gov.br -t 0 postRestURL "//?fmt=tgz&resolve=skip" /tmp/enfermagemx@cruzeiro.rs.gov.br-Junk.tgz
zmmailbox -z -m farmacias@cruzeiro.rs.gov.br -t 0 postRestURL "//?fmt=tgz&resolve=skip" /tmp/farmacias@cruzeiro.rs.gov.br-Junk.tgz
zmmailbox -z -m licita2@cruzeiro.rs.gov.br -t 0 postRestURL "//?fmt=tgz&resolve=skip" /tmp/licita2@cruzeiro.rs.gov.br-Junk.tgz
zmmailbox -z -m sec.saude@cruzeiro.rs.gov.br -t 0 postRestURL "//?fmt=tgz&resolve=skip" /tmp/sec.saude@cruzeiro.rs.gov.br-Junk.tgz
zmmailbox -z -m compras@cruzeiro.rs.gov.br -t 0 postRestURL "//?fmt=tgz&resolve=skip" /tmp/compras@cruzeiro.rs.gov.br-Junk.tgz
zmmailbox -z -m compras2@cruzeiro.rs.gov.br -t 0 postRestURL "//?fmt=tgz&resolve=skip" /tmp/compras2@cruzeiro.rs.gov.br-Junk.tgz
zmmailbox -z -m sistemasaude@cruzeiro.rs.gov.br -t 0 postRestURL "//?fmt=tgz&resolve=skip" /tmp/sistemasaude@cruzeiro.rs.gov.br-Junk.tgz
zmmailbox -z -m tributos@cruzeiro.rs.gov.br -t 0 postRestURL "//?fmt=tgz&resolve=skip" /tmp/tributos@cruzeiro.rs.gov.br-Junk.tgz
zmmailbox -z -m tributos3@cruzeiro.rs.gov.br -t 0 postRestURL "//?fmt=tgz&resolve=skip" /tmp/tributos3@cruzeiro.rs.gov.br-Junk.tgz
zmmailbox -z -m agricultura2x@cruzeiro.rs.gov.br -t 0 postRestURL "//?fmt=tgz&resolve=skip" /tmp/agricultura2x@cruzeiro.rs.gov.br-Junk.tgz
zmmailbox -z -m meioambiente3@cruzeiro.rs.gov.br -t 0 postRestURL "//?fmt=tgz&resolve=skip" /tmp/meioambiente3@cruzeiro.rs.gov.br-Junk.tgz
zmmailbox -z -m empenho@cruzeiro.rs.gov.br -t 0 postRestURL "//?fmt=tgz&resolve=skip" /tmp/empenho@cruzeiro.rs.gov.br-Junk.tgz
zmmailbox -z -m tesouraria@cruzeiro.rs.gov.br -t 0 postRestURL "//?fmt=tgz&resolve=skip" /tmp/tesouraria@cruzeiro.rs.gov.br-Junk.tgz
zmmailbox -z -m icms@cruzeiro.rs.gov.br -t 0 postRestURL "//?fmt=tgz&resolve=skip" /tmp/icms@cruzeiro.rs.gov.br-Junk.tgz
zmmailbox -z -m educa@cruzeiro.rs.gov.br -t 0 postRestURL "//?fmt=tgz&resolve=skip" /tmp/educa@cruzeiro.rs.gov.br-Junk.tgz
zmmailbox -z -m procuradoria@cruzeiro.rs.gov.br -t 0 postRestURL "//?fmt=tgz&resolve=skip" /tmp/procuradoria@cruzeiro.rs.gov.br-Junk.tgz
zmmailbox -z -m contabilidade@cruzeiro.rs.gov.br -t 0 postRestURL "//?fmt=tgz&resolve=skip" /tmp/contabilidade@cruzeiro.rs.gov.br-Junk.tgz
zmmailbox -z -m agricultura@cruzeiro.rs.gov.br -t 0 postRestURL "//?fmt=tgz&resolve=skip" /tmp/agricultura@cruzeiro.rs.gov.br-Junk.tgz
zmmailbox -z -m esf1@cruzeiro.rs.gov.br -t 0 postRestURL "//?fmt=tgz&resolve=skip" /tmp/esf1@cruzeiro.rs.gov.br-Junk.tgz
zmmailbox -z -m esf2@cruzeiro.rs.gov.br -t 0 postRestURL "//?fmt=tgz&resolve=skip" /tmp/esf2@cruzeiro.rs.gov.br-Junk.tgz
zmmailbox -z -m fiscal2@cruzeiro.rs.gov.br -t 0 postRestURL "//?fmt=tgz&resolve=skip" /tmp/fiscal2@cruzeiro.rs.gov.br-Junk.tgz
zmmailbox -z -m nutricao@cruzeiro.rs.gov.br -t 0 postRestURL "//?fmt=tgz&resolve=skip" /tmp/nutricao@cruzeiro.rs.gov.br-Junk.tgz
zmmailbox -z -m licita@cruzeiro.rs.gov.br -t 0 postRestURL "//?fmt=tgz&resolve=skip" /tmp/licita@cruzeiro.rs.gov.br-Junk.tgz
zmmailbox -z -m licitahsga@cruzeiro.rs.gov.br -t 0 postRestURL "//?fmt=tgz&resolve=skip" /tmp/licitahsga@cruzeiro.rs.gov.br-Junk.tgz
zmmailbox -z -m cultura@cruzeiro.rs.gov.br -t 0 postRestURL "//?fmt=tgz&resolve=skip" /tmp/cultura@cruzeiro.rs.gov.br-Junk.tgz
zmmailbox -z -m turismo@cruzeiro.rs.gov.br -t 0 postRestURL "//?fmt=tgz&resolve=skip" /tmp/turismo@cruzeiro.rs.gov.br-Junk.tgz
zmmailbox -z -m expocruzeiro@cruzeiro.rs.gov.br -t 0 postRestURL "//?fmt=tgz&resolve=skip" /tmp/expocruzeiro@cruzeiro.rs.gov.br-Junk.tgz
zmmailbox -z -m pessoalx@cruzeiro.rs.gov.br -t 0 postRestURL "//?fmt=tgz&resolve=skip" /tmp/pessoalx@cruzeiro.rs.gov.br-Junk.tgz
zmmailbox -z -m procuradoriaadjunta@cruzeiro.rs.gov.br -t 0 postRestURL "//?fmt=tgz&resolve=skip" /tmp/procuradoriaadjunta@cruzeiro.rs.gov.br-Junk.tgz
zmmailbox -z -m esporte@cruzeiro.rs.gov.br -t 0 postRestURL "//?fmt=tgz&resolve=skip" /tmp/esporte@cruzeiro.rs.gov.br-Junk.tgz
zmmailbox -z -m procuradoriageral@cruzeiro.rs.gov.br -t 0 postRestURL "//?fmt=tgz&resolve=skip" /tmp/procuradoriageral@cruzeiro.rs.gov.br-Junk.tgz
zmmailbox -z -m saudemental@cruzeiro.rs.gov.br -t 0 postRestURL "//?fmt=tgz&resolve=skip" /tmp/saudemental@cruzeiro.rs.gov.br-Junk.tgz
zmmailbox -z -m assessoriajuridica@cruzeiro.rs.gov.br -t 0 postRestURL "//?fmt=tgz&resolve=skip" /tmp/assessoriajuridica@cruzeiro.rs.gov.br-Junk.tgz
zmmailbox -z -m assistencia@cruzeiro.rs.gov.br -t 0 postRestURL "//?fmt=tgz&resolve=skip" /tmp/assistencia@cruzeiro.rs.gov.br-Junk.tgz
zmmailbox -z -m cras@cruzeiro.rs.gov.br -t 0 postRestURL "//?fmt=tgz&resolve=skip" /tmp/cras@cruzeiro.rs.gov.br-Junk.tgz
zmmailbox -z -m cpd@cruzeiro.rs.gov.br -t 0 postRestURL "//?fmt=tgz&resolve=skip" /tmp/cpd@cruzeiro.rs.gov.br-Junk.tgz
zmmailbox -z -m gabinete@cruzeiro.rs.gov.br -t 0 postRestURL "//?fmt=tgz&resolve=skip" /tmp/gabinete@cruzeiro.rs.gov.br-Junk.tgz
zmmailbox -z -m assessorprocuradoria@cruzeiro.rs.gov.br -t 0 postRestURL "//?fmt=tgz&resolve=skip" /tmp/assessorprocuradoria@cruzeiro.rs.gov.br-Junk.tgz
zmmailbox -z -m meioambiente@cruzeiro.rs.gov.br -t 0 postRestURL "//?fmt=tgz&resolve=skip" /tmp/meioambiente@cruzeiro.rs.gov.br-Junk.tgz
zmmailbox -z -m exames@cruzeiro.rs.gov.br -t 0 postRestURL "//?fmt=tgz&resolve=skip" /tmp/exames@cruzeiro.rs.gov.br-Junk.tgz
zmmailbox -z -m ivz2@cruzeiro.rs.gov.br -t 0 postRestURL "//?fmt=tgz&resolve=skip" /tmp/ivz2@cruzeiro.rs.gov.br-Junk.tgz
zmmailbox -z -m postoivz@cruzeiro.rs.gov.br -t 0 postRestURL "//?fmt=tgz&resolve=skip" /tmp/postoivz@cruzeiro.rs.gov.br-Junk.tgz
zmmailbox -z -m transito@cruzeiro.rs.gov.br -t 0 postRestURL "//?fmt=tgz&resolve=skip" /tmp/transito@cruzeiro.rs.gov.br-Junk.tgz
zmmailbox -z -m faturamento2hsga@cruzeiro.rs.gov.br -t 0 postRestURL "//?fmt=tgz&resolve=skip" /tmp/faturamento2hsga@cruzeiro.rs.gov.br-Junk.tgz
zmmailbox -z -m farmaciahsga@cruzeiro.rs.gov.br -t 0 postRestURL "//?fmt=tgz&resolve=skip" /tmp/farmaciahsga@cruzeiro.rs.gov.br-Junk.tgz
zmmailbox -z -m comprashsga@cruzeiro.rs.gov.br -t 0 postRestURL "//?fmt=tgz&resolve=skip" /tmp/comprashsga@cruzeiro.rs.gov.br-Junk.tgz
zmmailbox -z -m faturamentohsga@cruzeiro.rs.gov.br -t 0 postRestURL "//?fmt=tgz&resolve=skip" /tmp/faturamentohsga@cruzeiro.rs.gov.br-Junk.tgz
zmmailbox -z -m engenharia@cruzeiro.rs.gov.br -t 0 postRestURL "//?fmt=tgz&resolve=skip" /tmp/engenharia@cruzeiro.rs.gov.br-Junk.tgz
zmmailbox -z -m arquitetura@cruzeiro.rs.gov.br -t 0 postRestURL "//?fmt=tgz&resolve=skip" /tmp/arquitetura@cruzeiro.rs.gov.br-Junk.tgz
zmmailbox -z -m arquitetura2@cruzeiro.rs.gov.br -t 0 postRestURL "//?fmt=tgz&resolve=skip" /tmp/arquitetura2@cruzeiro.rs.gov.br-Junk.tgz
zmmailbox -z -m conselhotutelar@cruzeiro.rs.gov.br -t 0 postRestURL "//?fmt=tgz&resolve=skip" /tmp/conselhotutelar@cruzeiro.rs.gov.br-Junk.tgz
zmmailbox -z -m servicos@cruzeiro.rs.gov.br -t 0 postRestURL "//?fmt=tgz&resolve=skip" /tmp/servicos@cruzeiro.rs.gov.br-Junk.tgz
zmmailbox -z -m aviso@cruzeiro.rs.gov.br -t 0 postRestURL "//?fmt=tgz&resolve=skip" /tmp/aviso@cruzeiro.rs.gov.br-Junk.tgz
zmmailbox -z -m emefpassodeestrela@cruzeiro.rs.gov.br -t 0 postRestURL "//?fmt=tgz&resolve=skip" /tmp/emefpassodeestrela@cruzeiro.rs.gov.br-Junk.tgz
zmmailbox -z -m emefsaofelipe@cruzeiro.rs.gov.br -t 0 postRestURL "//?fmt=tgz&resolve=skip" /tmp/emefsaofelipe@cruzeiro.rs.gov.br-Junk.tgz
zmmailbox -z -m emeidoceinfancia@cruzeiro.rs.gov.br -t 0 postRestURL "//?fmt=tgz&resolve=skip" /tmp/emeidoceinfancia@cruzeiro.rs.gov.br-Junk.tgz
zmmailbox -z -m emeinovoscaminhos@cruzeiro.rs.gov.br -t 0 postRestURL "//?fmt=tgz&resolve=skip" /tmp/emeinovoscaminhos@cruzeiro.rs.gov.br-Junk.tgz
zmmailbox -z -m emeitrenzinhoalegre@cruzeiro.rs.gov.br -t 0 postRestURL "//?fmt=tgz&resolve=skip" /tmp/emeitrenzinhoalegre@cruzeiro.rs.gov.br-Junk.tgz
zmmailbox -z -m emeivilazwirtes@cruzeiro.rs.gov.br -t 0 postRestURL "//?fmt=tgz&resolve=skip" /tmp/emeivilazwirtes@cruzeiro.rs.gov.br-Junk.tgz
zmmailbox -z -m emeijacobsehn@cruzeiro.rs.gov.br -t 0 postRestURL "//?fmt=tgz&resolve=skip" /tmp/emeijacobsehn@cruzeiro.rs.gov.br-Junk.tgz
zmmailbox -z -m admhsga@cruzeiro.rs.gov.br -t 0 postRestURL "//?fmt=tgz&resolve=skip" /tmp/admhsga@cruzeiro.rs.gov.br-Junk.tgz
zmmailbox -z -m emef25dejulho@cruzeiro.rs.gov.br -t 0 postRestURL "//?fmt=tgz&resolve=skip" /tmp/emef25dejulho@cruzeiro.rs.gov.br-Junk.tgz
zmmailbox -z -m emefadelino@cruzeiro.rs.gov.br -t 0 postRestURL "//?fmt=tgz&resolve=skip" /tmp/emefadelino@cruzeiro.rs.gov.br-Junk.tgz
zmmailbox -z -m emefciceri@cruzeiro.rs.gov.br -t 0 postRestURL "//?fmt=tgz&resolve=skip" /tmp/emefciceri@cruzeiro.rs.gov.br-Junk.tgz
zmmailbox -z -m emefjacobsehn@cruzeiro.rs.gov.br -t 0 postRestURL "//?fmt=tgz&resolve=skip" /tmp/emefjacobsehn@cruzeiro.rs.gov.br-Junk.tgz
zmmailbox -z -m vigilanciasanitaria@cruzeiro.rs.gov.br -t 0 postRestURL "//?fmt=tgz&resolve=skip" /tmp/vigilanciasanitaria@cruzeiro.rs.gov.br-Junk.tgz
zmmailbox -z -m agendamento.passo@cruzeiro.rs.gov.br -t 0 postRestURL "//?fmt=tgz&resolve=skip" /tmp/agendamento.passo@cruzeiro.rs.gov.br-Junk.tgz
zmmailbox -z -m notafiscaleletronica@cruzeiro.rs.gov.br -t 0 postRestURL "//?fmt=tgz&resolve=skip" /tmp/notafiscaleletronica@cruzeiro.rs.gov.br-Junk.tgz
zmmailbox -z -m vigilanciaambiental@cruzeiro.rs.gov.br -t 0 postRestURL "//?fmt=tgz&resolve=skip" /tmp/vigilanciaambiental@cruzeiro.rs.gov.br-Junk.tgz
zmmailbox -z -m controleinterno@cruzeiro.rs.gov.br -t 0 postRestURL "//?fmt=tgz&resolve=skip" /tmp/controleinterno@cruzeiro.rs.gov.br-Junk.tgz
zmmailbox -z -m covid.passo@cruzeiro.rs.gov.br -t 0 postRestURL "//?fmt=tgz&resolve=skip" /tmp/covid.passo@cruzeiro.rs.gov.br-Junk.tgz
zmmailbox -z -m cras2@cruzeiro.rs.gov.br -t 0 postRestURL "//?fmt=tgz&resolve=skip" /tmp/cras2@cruzeiro.rs.gov.br-Junk.tgz
zmmailbox -z -m resultadoexameshsga@cruzeiro.rs.gov.br -t 0 postRestURL "//?fmt=tgz&resolve=skip" /tmp/resultadoexameshsga@cruzeiro.rs.gov.br-Junk.tgz
zmmailbox -z -m internet@cruzeiro.rs.gov.br -t 0 postRestURL "//?fmt=tgz&resolve=skip" /tmp/internet@cruzeiro.rs.gov.br-Junk.tgz
zmmailbox -z -m transporte@cruzeiro.rs.gov.br -t 0 postRestURL "//?fmt=tgz&resolve=skip" /tmp/transporte@cruzeiro.rs.gov.br-Junk.tgz
zmmailbox -z -m parque@cruzeiro.rs.gov.br -t 0 postRestURL "//?fmt=tgz&resolve=skip" /tmp/parque@cruzeiro.rs.gov.br-Junk.tgz
zmmailbox -z -m engenharial@cruzeiro.rs.gov.br -t 0 postRestURL "//?fmt=tgz&resolve=skip" /tmp/engenharial@cruzeiro.rs.gov.br-Junk.tgz
zmmailbox -z -m emergenciahsga@cruzeiro.rs.gov.br -t 0 postRestURL "//?fmt=tgz&resolve=skip" /tmp/emergenciahsga@cruzeiro.rs.gov.br-Junk.tgz
zmmailbox -z -m coordenacaosecsaude@cruzeiro.rs.gov.br -t 0 postRestURL "//?fmt=tgz&resolve=skip" /tmp/coordenacaosecsaude@cruzeiro.rs.gov.br-Junk.tgz
zmmailbox -z -m fiscal@cruzeiro.rs.gov.br -t 0 postRestURL "//?fmt=tgz&resolve=skip" /tmp/fiscal@cruzeiro.rs.gov.br-Junk.tgz
zmmailbox -z -m eliana@cruzeiro.rs.gov.br -t 0 postRestURL "//?fmt=tgz&resolve=skip" /tmp/eliana@cruzeiro.rs.gov.br-Junk.tgz
zmmailbox -z -m silvana@cruzeiro.rs.gov.br -t 0 postRestURL "//?fmt=tgz&resolve=skip" /tmp/silvana@cruzeiro.rs.gov.br-Junk.tgz
zmmailbox -z -m fabiane@cruzeiro.rs.gov.br -t 0 postRestURL "//?fmt=tgz&resolve=skip" /tmp/fabiane@cruzeiro.rs.gov.br-Junk.tgz
zmmailbox -z -m dalva@cruzeiro.rs.gov.br -t 0 postRestURL "//?fmt=tgz&resolve=skip" /tmp/dalva@cruzeiro.rs.gov.br-Junk.tgz
zmmailbox -z -m zeli@cruzeiro.rs.gov.br -t 0 postRestURL "//?fmt=tgz&resolve=skip" /tmp/zeli@cruzeiro.rs.gov.br-Junk.tgz
zmmailbox -z -m grasiela@cruzeiro.rs.gov.br -t 0 postRestURL "//?fmt=tgz&resolve=skip" /tmp/grasiela@cruzeiro.rs.gov.br-Junk.tgz
zmmailbox -z -m mirtes@cruzeiro.rs.gov.br -t 0 postRestURL "//?fmt=tgz&resolve=skip" /tmp/mirtes@cruzeiro.rs.gov.br-Junk.tgz
zmmailbox -z -m fernanda@cruzeiro.rs.gov.br -t 0 postRestURL "//?fmt=tgz&resolve=skip" /tmp/fernanda@cruzeiro.rs.gov.br-Junk.tgz
zmmailbox -z -m jaqueline@cruzeiro.rs.gov.br -t 0 postRestURL "//?fmt=tgz&resolve=skip" /tmp/jaqueline@cruzeiro.rs.gov.br-Junk.tgz
zmmailbox -z -m haide@cruzeiro.rs.gov.br -t 0 postRestURL "//?fmt=tgz&resolve=skip" /tmp/haide@cruzeiro.rs.gov.br-Junk.tgz
zmmailbox -z -m elis@cruzeiro.rs.gov.br -t 0 postRestURL "//?fmt=tgz&resolve=skip" /tmp/elis@cruzeiro.rs.gov.br-Junk.tgz
zmmailbox -z -m juliana@cruzeiro.rs.gov.br -t 0 postRestURL "//?fmt=tgz&resolve=skip" /tmp/juliana@cruzeiro.rs.gov.br-Junk.tgz
zmmailbox -z -m beatriz@cruzeiro.rs.gov.br -t 0 postRestURL "//?fmt=tgz&resolve=skip" /tmp/beatriz@cruzeiro.rs.gov.br-Junk.tgz
zmmailbox -z -m noemia@cruzeiro.rs.gov.br -t 0 postRestURL "//?fmt=tgz&resolve=skip" /tmp/noemia@cruzeiro.rs.gov.br-Junk.tgz
zmmailbox -z -m marli@cruzeiro.rs.gov.br -t 0 postRestURL "//?fmt=tgz&resolve=skip" /tmp/marli@cruzeiro.rs.gov.br-Junk.tgz
zmmailbox -z -m meioambiente2@cruzeiro.rs.gov.br -t 0 postRestURL "//?fmt=tgz&resolve=skip" /tmp/meioambiente2@cruzeiro.rs.gov.br-Junk.tgz
zmmailbox -z -m assistenciasocialsaude@cruzeiro.rs.gov.br -t 0 postRestURL "//?fmt=tgz&resolve=skip" /tmp/assistenciasocialsaude@cruzeiro.rs.gov.br-Junk.tgz
zmmailbox -z -m vigilanciaepidemiologica@cruzeiro.rs.gov.br -t 0 postRestURL "//?fmt=tgz&resolve=skip" /tmp/vigilanciaepidemiologica@cruzeiro.rs.gov.br-Junk.tgz
zmmailbox -z -m denunciascovid19@cruzeiro.rs.gov.br -t 0 postRestURL "//?fmt=tgz&resolve=skip" /tmp/denunciascovid19@cruzeiro.rs.gov.br-Junk.tgz
zmmailbox -z -m engenharia2@cruzeiro.rs.gov.br -t 0 postRestURL "//?fmt=tgz&resolve=skip" /tmp/engenharia2@cruzeiro.rs.gov.br-Junk.tgz
zmmailbox -z -m juntamilitar@cruzeiro.rs.gov.br -t 0 postRestURL "//?fmt=tgz&resolve=skip" /tmp/juntamilitar@cruzeiro.rs.gov.br-Junk.tgz
zmmailbox -z -m ti@cruzeiro.rs.gov.br -t 0 postRestURL "//?fmt=tgz&resolve=skip" /tmp/ti@cruzeiro.rs.gov.br-Junk.tgz
zmmailbox -z -m cmas@cruzeiro.rs.gov.br -t 0 postRestURL "//?fmt=tgz&resolve=skip" /tmp/cmas@cruzeiro.rs.gov.br-Junk.tgz
zmmailbox -z -m spfbl@cruzeiro.rs.gov.br -t 0 postRestURL "//?fmt=tgz&resolve=skip" /tmp/spfbl@cruzeiro.rs.gov.br-Junk.tgz
zmmailbox -z -m habitacao@cruzeiro.rs.gov.br -t 0 postRestURL "//?fmt=tgz&resolve=skip" /tmp/habitacao@cruzeiro.rs.gov.br-Junk.tgz
zmmailbox -z -m cartaosus@cruzeiro.rs.gov.br -t 0 postRestURL "//?fmt=tgz&resolve=skip" /tmp/cartaosus@cruzeiro.rs.gov.br-Junk.tgz
zmmailbox -z -m mariela@cruzeiro.rs.gov.br -t 0 postRestURL "//?fmt=tgz&resolve=skip" /tmp/mariela@cruzeiro.rs.gov.br-Junk.tgz
zmmailbox -z -m nilvarbc@cruzeiro.rs.gov.br -t 0 postRestURL "//?fmt=tgz&resolve=skip" /tmp/nilvarbc@cruzeiro.rs.gov.br-Junk.tgz
zmmailbox -z -m farmacia@cruzeiro.rs.gov.br -t 0 postRestURL "//?fmt=tgz&resolve=skip" /tmp/farmacia@cruzeiro.rs.gov.br-Junk.tgz
zmmailbox -z -m pregao@cruzeiro.rs.gov.br -t 0 postRestURL "//?fmt=tgz&resolve=skip" /tmp/pregao@cruzeiro.rs.gov.br-Junk.tgz
zmmailbox -z -m transportesaude@cruzeiro.rs.gov.br -t 0 postRestURL "//?fmt=tgz&resolve=skip" /tmp/transportesaude@cruzeiro.rs.gov.br-Junk.tgz
zmmailbox -z -m estagiariajuridico@cruzeiro.rs.gov.br -t 0 postRestURL "//?fmt=tgz&resolve=skip" /tmp/estagiariajuridico@cruzeiro.rs.gov.br-Junk.tgz
